### ISSUE TITLE
PDF generation 0 bytes

### ISSUE THREAD

**Issue by MrMarioMichel** [immauss/openvas#85]
Seems that in the latest version PDF generation is not working correctly (Files have 0 bytes in size)

```
openvas    | md manage:WARNING:2021-11-12 12h28.28 UTC:833: run_report_format_script: system failed with ret 256, 1, /var/lib/gvm/gvmd/report_formats/c00c685f-1415-48fd-b3b4-d7bdae0daba7/c402cc3e-b531-11e1-9163-406186ea4fc5/generate /tmp/gvmd_2QT92Q/report.xml '<files><basedir>/tmp/gvmd_2QT92Q</basedir></files>' > /tmp/gvmd_2QT92Q/c402cc3e-b531-11e1-9163-406186ea4fc5-c6jTCM.pdf 2> /dev/null

```

![image](https://user-images.githubusercontent.com/30075959/141467243-a547a08f-5e3c-4d31-a3c3-fb88f303b68c.png)

**Comment by immauss** [comment]
This should be fixed in the latest image. There was a dependency missing.

**Comment by MrMarioMichel** [comment]
Hmmm seems that the latest version just exits out without any logs.

```
Attaching to openvas
openvas exited with code 0
```

**Comment by cybermcm** [comment]
container exit with no log: related to https://github.com/immauss/openvas/issues/83 and https://github.com/immauss/openvas/issues/84
just wait for the new image, the pdf issue was already fixed in 21.4.4-03

**Comment by cybermcm** [comment]
you can try latest now, pdf report is working there

**Comment by MrMarioMichel** [comment]
Sadly still the same issue in 21.4.4-05. Also tried with latest docker [release](https://hub.docker.com/layers/immauss/openvas/latest/images/sha256-e1c0c0c2ba205bfbdf0177c8e9fb42839898ded4bd98429887ee95fb850a384a?context=explore) and this is what happens.

```
openvas    | Wait for redis socket to be created...
openvas    | Container stopped, performing shutdown
openvas    | pg_ctl: PID file "/data/database/postmaster.pid" does not exist
openvas    | Is server running?
openvas    | Wait for redis socket to be created...
```

**Comment by cybermcm** [comment]
yeah, seems that @immauss broke it again, yesterday's latest was working, today's is not...
I'm sure he'll fix it soon

**Comment by MrMarioMichel** [comment]
No worries @immauss you are doing a great job. Thank you for the docker images!

**Comment by MrMarioMichel** [comment]
@immauss 
The version 21.4.4-06 seems to fix the broken PDF generation and creates PDF files again as expected!

I think you can close this issue!

**Comment by immauss** [comment]
Awesome! 
Thank you for the follow up.
